---
title: "Project 3: STAT302package Tutorial"
author: Cherry Pan & Yi-Hsuan Wu
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{STAT302package Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(STAT302package)
```


```{r my_rf_cv}
# Attach libraries used for this part of tutorial
library(dplyr)
library(randomForest)
library(ggplot2)
library(kableExtra)
# run functions for 30 times with k = 2, 5, 10.
cv_2 <- replicate(30, my_rf_cv(2))
cv_5 <- replicate(30, my_rf_cv(5))
cv_10 <- replicate(30, my_rf_cv(10))
# Store results as a data frame
cv_df <- data.frame("k" = c(rep(2,30),rep(5,30), rep(10,30)),
                 "cv" = c(cv_2,cv_5,cv_10))
# Plot the results as a boxplot
cv_plot <- ggplot(cv_df, aes(factor(k), cv)) +
  geom_boxplot() +
  labs(x = c("k"), y = c("CV estimated MSE"))
cv_plot
# Display table with 
cv_table <- data.frame("k" = c(2, 5, 10),
                       "Mean" = c(mean(cv_2),mean(cv_5),mean(cv_10)),
                       "Standard Deviation" = c(sd(cv_2),sd(cv_5),sd(cv_10)))
kable_styling(kable(cv_table))
                       
```

From the boxplot, it's observed that CV estimated MSE has greatest mean when k = 2,
which is above 120000. However, by inspecting the table, we can see standard deviation
of CV estimated MSE is greatest when k = 10. The reason may be due to that 2 folds 
yield  greatest MSE and 5 folds yield greatest variance in this data set.

